name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: './node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Run type checks (TypeScript)
        run: yarn --ignore-scripts tsc

      - name: Run linter (ESLint)
        run: yarn --ignore-scripts lint
